### ISSUE TITLE
Sharings

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-notes#104]
Mettre à jour cozy-sharings car aujourd'hui si on a plus de 30 partages par Lien et qu'on partage une note, on a de grande chance de ne plus voir que la note est partagée

**Comment by y-lohse** [comment]
A noter qu'avec la version 1.11.0, on pourra enlever les `withLocales` autour des composants de cozy-sharings, ceci étant directement exportés avec la bonne locale.
