### ISSUE TITLE
Test command is broken

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-notes#13]
The test command currently returns an error code 1, because no tests can be found.

I tried to add a dummy test, which it ran but then crashed with the error 

```
TypeError: Expected a string

      at Object.<anonymous>.module.exports (node_modules/escape-string-regexp/index.js:7:9)
      at Object.<anonymous> (node_modules/chalk/index.js:72:39)
```

Note sure where this comes from, [`ansiStyles.color.close`](https://github.com/chalk/chalk/blob/v2-release/index.js#L72) really is `undefined` on my machine, but I would say it's likely a dependency problem more than an actual problem in chalk.

**Comment by Crash--** [comment]
https://github.com/cozy/cozy-notes/pull/39
