### ISSUE TITLE
In local, clicking on the "add new note" redirect the user to the page "Application not yet available"

### ISSUE THREAD

**Issue by cricrio** [cozy/cozy-notes#336]
I followed the steps mentioned in the README file to start the application.

The app is available at http://app.cozy.localhost:8080/ but when I'm clicking on the "Add new note" i'm redirected to http://notes.cozy.localhost:8080/?returnUrl=http%3A%2F%2Fapp.cozy.localhost%3A8080%2F#/n/f0f1b0fc25b1265b4ef08fcd60008dff. The page display this message: "Application not yet available".
 
I have found a workaround by adding a 'notes' volume in the stack:docker:dev command.
`    "stack:docker:dev": "COZY_STACK_HOST=cozy.localhost docker run --rm -it -p 8080:8080 -p 5984:5984 -e COZY_DISABLE_CSP=1 -v $(pwd)/build:/data/cozy-app/app -v $(pwd)/build:/data/cozy-app/notes cozy/cozy-app-dev",
`
I'm not sure if it's the correct way to fix this issue.

**Comment by Crash--** [comment]
Hi @cricrio, 

Thanks for reporting the issue. I think this is the right way to fix the issue. (We don't have it internally, because we don't use the docker image). 

Do you want to submit the PR? :)

**Comment by cricrio** [comment]
Yes!
